services:
  shulker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shulker_app
    ports:
      - "8000:8000"
    volumes:
      - /app:${LOCAL_REPO_PATH}
      - /app/logs:${LOG_PATH}
    restart: unless-stopped
