version: '3.8'

services:
  shulker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shulker_app
    ports:
      - "8000:8000"
    volumes:
      - ${LOCAL_REPO_PATH}:/app
      - ${LOG_PATH}:/app/logs
    restart: unless-stopped
